server:
  port: ${COST_CALCULATION_PORT:8083}

spring:
  application:
    name: CostCalculation

  datasource:
    url: jdbc:mysql://${COST_CALCULATION_MYSQL_DB_HOST:localhost}:${COST_CALCULATION_MYSQL_DB_PORT:3306}/${COST_CALCULATION_MYSQL_DB_COLLECTION:material_db}
    username: ${COST_CALCULATION_MYSQL_DB_USER:appuser}
    password: ${COST_CALCULATION_MYSQL_DB_PASSWORD:apppass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  services:
    application: ${APPLICATION_SERVICE_HOST:http://localhost:8084}
    user: ${USER_SERVICE_HOST:http://localhost:8081}
    material-price: ${MATERIAL_PRICE_SERVICE_HOST:http://localhost:8082}
    cost-calculation: ${COST_CALCULATION_SERVICE_HOST:http://localhost:8083}
    frontend: ${FRONTEND_CLIENT_URL:https://msametiz96.ru}

logging:
  level:
    com.calculator: DEBUG
    org.springframework.web: INFO
